board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path
from . import views # '.' 대신 'todos'를 써도 된다. '.' : 같은 폴더

# app을 여러개 생성해 줄 수 있기 때문에 app_name으로 묶어준 후 변수를 설정해주는 편이 좋다.
app_name = 'todos'

urlpatterns = [
    # Read
    path('', views.index, name="index"),
    # Create
    path('new/', views.new, name="new"), # new/라는 경로를 new라는 변수에 저장해서 사용한다.
    path('create/', views.create, name="create"),
    # new + create
    path('add/', views.add, name="add"),
    # Delete
    path('<int:id>/delete/', views.delete, name="delete"),
    # Update
    path('<int:id>/update/', views.update, name="update"),
]

todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=50) # 짧은 형태의 글
    content = models.TextField() # 긴 형태의 글 # django에서 TextField는 form 클래스에서 크기조절이 가능한 큰 상자가 생긴다.
    due_date = models.DateField()
    author = models.CharField(max_length=50)

todos/views.py
from django.shortcuts import render, redirect
from .models import Todo # '.models' 대신 'todos.models'를 사용해도 된다.

# Create your views here.
def index(request):
    todos = Todo.objects.all()
    context = {
        'todos': todos,
    }
    return render(request, 'index.html', context)

def new(request):
    return render(request, 'new.html')

def create(request):
    author = request.POST.get('author')
    title = request.POST.get('title')
    content = request.POST.get('content')
    due_date = request.POST.get('due-date')

    # todo = Todo()
    # todo.author = author
    # todo.title = title
    # todo.content = content
    # todo.due_date = due_date
    # todo.save() # 바로 저장하지 않고 쓰일때 사용

    # create는 안에 인스턴스를 만들고 생성까지 해준다.
    todo = Todo.objects.create(
        author=author,
        title=title,
        content=content,
        due_date=due_date,
    )
    return redirect('todos:index') # '/todos/' 대신 사용한다.

def delete(request, id):
    todo = Todo.objects.get(id=id)
    todo.delete()
    return redirect('todos:index')

def add(request):
    if request.method == "POST":
        author = request.POST.get('author')
        title = request.POST.get('title')
        content = request.POST.get('content')
        due_date = request.POST.get('due-date')

        todo = Todo.objects.create(
            author=author,
            title=title,
            content=content,
            due_date=due_date,
        )
        return redirect('todos:index')
    else:
        return render(request, 'add.html')

def update(request, id):
    todo = Todo.objects.get(id=id)
    if request.method == "POST":
        author = request.POST.get('author')
        title = request.POST.get('title')
        content = request.POST.get('content')
        due_date = request.POST.get('due-date')

        # todo = Todo(id=id, author=author, title=title, content=content, due_date=due_date)
        # todo = Todo.objects.get(id=id) # if문과 else문에 공통으로 들어가므로 if문 밖에 쓰면 된다.
        todo.author = author
        todo.title = title
        todo.content = content
        todo.due_date = due_date
        todo.save()
        return redirect('todos:index')
    else:
        # 수정을 하려면 기존의 정보를 가져와야 한다.
        # todo = Todo.objects.get(id=id) # if문과 else문에 공통으로 들어가므로 if문 밖에 쓰면 된다.
        context = {
            'todo': todo,
        }
        return render(request, 'update.html', context)

todos/templates/add.html
{% extends 'base.html' %}

{% block body %}
  <!-- action이 빈칸일 경우 제자리에 있게 된다. -->
  <form action="" method="post">
    <!-- 'csrf_token'은 django 안에서 들어오는 input값을 hidden으로 처리해준다. -->
    {% csrf_token %}
    작성자: <input type="text" name="author">
    제목 : <input type="text" name="title">
    내용 : <input type="text" name="content">
    마감일 : <input type="date" name="due-date">
    <input type="submit" value="저장">
  </form>
{% endblock %}

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Todo</title>
</head>
<body>
  <a href="{% url 'todos:index' %}">전체글보기</a>
  <a href="{% url 'todos:new' %}">할일추가</a>
  <a href="{% url 'todos:add' %}">할일추가(합쳐진코드)</a>
  {% block body %}
  {% endblock %}
</body>
</html>

todos/templates/index.html
{% extends 'base.html' %}

{% block body %}
  <h1>index</h1>
  {% for todo in todos %}
    <h5>{{todo.author}}/{{todo.title}} - {{todo.due_date}}</h5>
    <a href="{% url 'todos:delete' todo.id %}">삭제</a>
    <a href="{% url 'todos:update' todo.id %}">수정</a>
  {% endfor %}
{% endblock %}

todos/templates/new.html
{% extends 'base.html' %}

{% block body %}
  <!-- form method의 기본값은 "get" -->
  <!-- get: 데이터를 가져와서 보여주는 역할 -->
  <!-- post: 데이터를 보내면 서버에서 처리해주는 역할 (CRUD)) -->
  <form action="{% url 'todos:create' %}" method="post">
    <!-- 'csrf_token'은 django 안에서 들어오는 input값을 hidden으로 처리해준다. -->
    {% csrf_token %}
    작성자: <input type="text" name="author">
    제목 : <input type="text" name="title">
    내용 : <input type="text" name="content">
    마감일 : <input type="date" name="due-date">
    <input type="submit" value="저장">
  </form>
{% endblock %}

todos/templates/update.html
{% extends 'base.html' %}

{% block body %}
  <form action="" method="post">
    <!-- 'csrf_token'은 django 안에서 들어오는 input값을 hidden으로 처리해준다. -->
    {% csrf_token %}
    작성자: <input type="text" name="author" value="{{todo.author}}">
    제목 : <input type="text" name="title" value="{{todo.title}}">
    내용 : <input type="text" name="content" value="{{todo.content}}">
    마감일 : <input type="date" name="due-date" value="{{todo.due_date|date:'Y-m-d'}}">
    <input type="submit" value="저장">
  </form>
{% endblock %}